### ISSUE TITLE
gems: mentioned twice in _config.yml

### ISSUE THREAD

**Issue by studioromeo** [daviddarnes/daviddarnes.github.io#10]
See https://github.com/daviddarnes/daviddarnes.github.io/blob/master/_config.yml#L2 & https://github.com/daviddarnes/daviddarnes.github.io/blob/master/_config.yml#L40

**Comment by daviddarnes** [comment]
![What a noob](https://c2.staticflickr.com/8/7081/7396371564_828beac495_z.jpg)
Will sort as soon as possible.
