### ISSUE TITLE
question on Jekyll

### ISSUE THREAD

**Issue by nservant** [daviddarnes/daviddarnes.github.io#21]
Hi David,
First many thanks for sharing this code which exactly does what I would like to do for my organization site. In addition, I would like to add the `avatar_url` of the contributors for each public repo.
I'm not an expert in Jekyll ... and I did not find how to do it.

So far, I tried ;
```
  {% for repo in site.github.public_repositories %}
    {% for member in repo.contributors_url %}
    <p><strong>login:</strong> {{ member.login }}</p>
    <p><strong>avatar_url:</strong> {{ member.avatar_url }}</p>
  {% endfor %}
{% endfor %}
```

But it doesn't work. If you have a few advices, it will be highly appreciated !
Thanks
Nicolas

**Comment by daviddarnes** [comment]
Oh sorry @nservant! I've only just seen this, I don't really check issues on this repo. Only a couple of years late 😅. Did you fix this?

**Comment by nservant** [comment]
:) I didn't test that for a while and will not look at it in the coming months but I guess I still have this issue ... if you want to have a look at it ! Thanks

**Comment by daviddarnes** [comment]
Best way to go about this to refer to this site https://jekyll.github.io/github-metadata/ and to utilise the `jsonify` filter which you can use alongside whatever object you're trying to expose data from. In this case you could do something like `{{ member | jsonify }}` and it'll output everything inside that object, from there you can pick out the keys you're looking for. Hope this helps!
