### ISSUE TITLE
Missing Page

### ISSUE THREAD

**Issue by epreston** [daviddarnes/daviddarnes.github.io#23]
I took the red pill and now I'm here, I was looking for [https://daviddarnes.github.io/splashed](https://daviddarnes.github.io/splashed) but it wasn't there...

... It's cold.  Wear a jacket when you go outside.

(this issue is based on your 404 template.  I think it's very creative and wanted to play along.)

**Comment by daviddarnes** [comment]
Haha thanks @epreston! Splashed had to be turned off since it received 2,273 entries and was becoming impossible to manage 😅
